[WIP] Fix errors with assert in tests under php8
phpsu/ShellCommandBuilder pull request #17
Opened 2020-10-26 07:24 UTC by dshoreman

## Description and Background

With the recent changes in ChrisB9/php8-xdebug that fix xdebug options, update composer and (afaict) remove the profiler that caused errors previously, there seem to be only two errors remaining in the tests on PHP 8.

Both errors are with the `assert()` lines, which throw an `AssertionError` in v8, but only trigger a warning (converted to `ErrorException` in tests/phpunit-bootstrap.php) when ran under v7. This is caused by a change to the defaults in v8 which now enable the `assert.exception` option by default.

I considered a couple methods, but simply enabling the option by default seems to be the cleanest route. The option itself was added in v7, so this change just makes things consistent across both versions.

## How Has This Been Tested
Existing tests fixed, ran with `docker-compose run php composer test && docker-compose run php8 composer test`.

Psalm is happy, but the infection tests are currently failing as a result of xdebug connection issues, but that's probably just a case of enabling some of the new options for the php8-xdebug image. I've yet to play with that; watch this space.

#### Checklist

- [x] My code follows the PSR coding guideline.
- [x] I have updated the `documentation` accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added `tests` to cover my changes.
- [x] All new and existing tests passed.

Fixes #15

2020-10-26 09:32 UTC, dshoreman commented
The grumphp-config Composer dep was blocking Travis build due to lack of composer-2 support, so I've updated it to 4.0.1 which adds compatibility for it.

Now it's running again, it looks like the errors I'm getting locally with the infection tests (xdebug could not connect to debugging client) are also happening in Travis, albeit only for php nightly.

I've tried updating the `EXPOSE` line from `9000` to `9003` locally in the php8-xdebug docker file (and updating docker-compose.yaml of this repo to use the local test image) but I think I'm missing a piece of the puzzle. 
I noticed some aliases/functions were added to the `.bashrc` in ChrisB9/php8-xdebug to enable/toggle xdebug, but I'm not sure how to call those from this repo to enable it if needed.

Any ideas? Once the infection tests are fixed, php8 support is probably good - seems the assert handling is the only thing that really changed. Were there any key things that needed doing/fixing beyond the xdebug bugs?

2020-10-29 11:06 UTC, ChrisB9 commented
Thanks alot for your effort.
I think a major issue is, that the dependencies are not all PHP 8.0 ready and that may cause troubles on all fronts.
I might actually already merge this because the tests are running and the only reason why infection doesn't work is due to external factors. Maybe though we could first extend the dependencies here or extract that into a second pull request? Such as phpunit ^9.0, psalm ^4.0, infection ^0.19 and php-invoker ^3.0. (I know it will fail thanks to grumphp and webmozart/glob but both will add PHP 8.0 support soon.

2020-10-30 09:42 UTC, dshoreman commented
I've just updated phpunit to 9.x and (so far) it's still green, although there are some new warnings now:

```
[snipped xdebug errors - see below]
PHPUnit 9.4.2 by Sebastian Bergmann and contributors.

Warning:       xdebug.mode=coverage has to be set in php.ini
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

Error:         PHP extension pcntl is required for enforcing time limits
```

Running the migration command has kindly removed most line breaks so I gotta fix that before I can diff them, but with any luck we won't need to adjust *too* much.

Assuming the phpunit stuff goes well, I'll push that up then see if there's time to look at the rest before I pass out

---

For reference, these are the xdebug warnings from php itself:

```

Creating shellcommandbuilder_php8_run ... done
Xdebug: [Step Debug] Could not connect to debugging client. Tried: internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
Xdebug: [Profiler] File '/tmp/debug/cachegrind.out.1' could not be opened.
> vendor/bin/phpunit -c tests/phpunit.xml --testdox --color=always
Xdebug: [Step Debug] Could not connect to debugging client. Tried: internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
Xdebug: [Profiler] File '/tmp/debug/cachegrind.out.12' could not be opened.
```

2020-10-30 13:38 UTC, ChrisB9 commented
Regarding the XDebug error. It seems like this error happens because XDebug cannot establish a connection to PHPStorm.
https://3.xdebug.org/docs/step_debug#log
I changed the XDebug default settings disabling debug by default.
https://github.com/ChrisB9/php8-xdebug/pull/8/files

2020-10-30 14:51 UTC, dshoreman commented
That would make sense as I don't have PHPStorm installed :D  
Thanks for the update. I'll pull the new docker bits later and give it a try, but that might just be all the warnings taken care of.

The "cachegrind.out" and /tmp/debug errors can be solved easily a couple ways, depending which you prefer:

1. Add `./tests/xdebug:/tmp/debug` (or similar) to `volumes:` list in ShellCommandBuilder/docker-compose.yml
   * How I fixed it locally (for now), seems to do the job
   * The debug dir requires 775 permissions, so it'd need to be tracked in git
   * To avoid unecessary cruft, `./tests/xdebug/*` would be added to .gitignore

2. Same as above, but in the php8-xdebug repo

3. `RUN mkdir /tmp/debug && chmod 775 $_` somewhere in php8-xdebug/php-dev-8.dockerfile

Option 3 *could* be the better route? But I'm not sure if other tools need to access the profiling data. If they do then we might need to go with option 1 regardless, in which case I can add it to this PR.

The only other question is that of the PHP minimum version. Phpunit requires `>=7.3` and infection requires `^7.4 || ^8`, but for now since both are dev-deps I think we'd be able to stay on 7.2 to avoid also updating that container. With 7.2 at EOL though, bumping that to 7.3 or .4 could be something for the future.

2020-10-30 15:07 UTC, ChrisB9 commented
I actually added this line too 
`RUN mkdir /tmp/debug && chmod 775 $_ somewhere in php8-xdebug/php-dev-8.dockerfile`

2020-10-31 12:49 UTC, dshoreman commented
It turns out the chmod isn't actually needed when it's created directly in php-dev-8.dockerfile. I should've tested that beforehand, sorry! Good news though is everything's running smooth from what I can see.

I've updated phpunit and infection locally and both are now running without issue. Infection flagged one issue so I've added a test to solve that too.

PHP 8 has removed pcntl (used for timing) from core due to lack of maintainers, so I've added that (and removed the aforementioned `chmod`) among some other cleanup which I'll post in a PR to php8-xdebug shortly.

If there's anything that needs changing in that PR first, please let me know and I'll get to it asap - I'll hold pushes to this PR until that's merged in case the pcntl error ends up causing CI to fail

2020-10-31 13:09 UTC, ChrisB9 commented
I just merged it, so let's see whether this now works. Thanks for digging into this!

2020-10-31 13:17 UTC, dshoreman commented
No worries, thanks for the fast merge! I'll get the commits pushed right now... :pray:

2020-10-31 14:22 UTC, dshoreman commented
Forgot about infection requiring 7.4, so I've added `--ignore-platform-reqs` to those versions in .travis.yml. I did try removing it from nightly too, but spatie/phpunit-watcher still trips that with a `^7.2` requirement.

Tests themselves are running again, but there's still some work to get coverage/infection working on Travis. I'll dig into that some more either today/tomorrow and update the PR if I figure anything out.

7.2 tests seem to only be failing currently due to latest infection using newer syntax (guessing trailing commas). We could just disable the infection task under 7.2? If that sounds good, I can add it in while I'm playing with the coverage bits.

Turning out to be quite the adventure, but... I think we're getting there!

2020-10-31 16:09 UTC, ChrisB9 commented
> did try removing it from nightly too, but spatie/phpunit-watcher still trips that with a ^7.2 requirement.

For phpunit-watcher, I quickly created a pull request to their repository https://github.com/spatie/phpunit-watcher/pull/124 so that we can omit `--ignore-platform-reqs`

> 7.2 tests seem to only be failing currently due to latest infection using newer syntax (guessing trailing commas). We could just disable the infection task under 7.2? If that sounds good, I can add it in while I'm playing with the coverage bits.

I wish I could drop 7.2 support altogether but sadly phpsu and our agency needs it.
Which line is the culprit for those failing infections?

> Turning out to be quite the adventure, but... I think we're getting there!
That's great, I am sure we will get to the bottom of this

2020-10-31 16:57 UTC, dshoreman commented
The issue in 7.2 isn't failing infections, but Infection PHP *itself* using syntax that's incompatible with 7.2:
```
$ composer infection

> vendor/bin/infection --threads=4 --only-covered --min-msi=100 --min-covered-msi=100 --ansi

PHP Parse error:  syntax error, unexpected ')' in /home/travis/build/phpsu/ShellCommandBuilder/vendor/infection/infection/src/Container.php on line 223

Parse error: syntax error, unexpected ')' in /home/travis/build/phpsu/ShellCommandBuilder/vendor/infection/infection/src/Container.php on line 223

Script vendor/bin/infection --threads=4 --only-covered --min-msi=100 --min-covered-msi=100 --ansi handling the infection event returned with error code 255
```

My first thought was infection simply wouldn't run, but seeing your PR to phpunit-watcher hinted at an `^A | ^B` syntax for Composer's version specifiers. That's *especially* useful now because I only just realised phpunit was also refusing to run on 7.2:

```
$ composer test

> vendor/bin/phpunit -c tests/phpunit.xml --testdox --color=always

This version of PHPUnit is supported on PHP 7.3 and PHP 7.4.

You are using PHP 7.2.27 (/home/travis/.phpenv/versions/7.2.27/bin/php).

Script vendor/bin/phpunit -c tests/phpunit.xml --testdox --color=always handling the test event returned with error code 1

The command "composer test" exited with 1.
```

I'll try updating the composer.json to accept either version for phpunit and infection, hopefully that should sort it without having to exclude 7.2 from the infection/phpunit runs.

2020-11-01 10:54 UTC, dshoreman commented
Some 30 builds and one sleep later, Travis is *finally* happy across all 7.x jobs. Huzzah!

Still got some work to do for the nightly job to pass, but once it does I'll rebase to clean up the huge string of commits then remove the `allow_failures` flag for php8.

2020-11-02 10:58 UTC, ChrisB9 commented
@dshoreman I see you did work quite a lot on it this weekend :D 
Can you give me a notice once you are ready?

2020-11-02 19:15 UTC, dshoreman commented
> @dshoreman I see you did work quite a lot on it this weekend :D

It looks like a lot but by the time it's rebased I'm sure it'll be much less :laughing: 

> Can you give me a notice once you are ready?

Sure, will do. Had planned to finish it this morning but something came up so if I don't get time tonight, could be next day or two.

2020-11-05 12:50 UTC, dshoreman commented
@ChrisB9 I've removed `allow-failures` from nightly builds, but we're still waiting on a couple dependencies before we can remove `--ignore-platform-reqs` entirely from composer.

It all seems to be working fine though, so I'll create a separate issue with the details on that. Think this is finally good to review! :tada:

2020-11-05 15:50 UTC, ChrisB9 requested changes
Looks good so far
Thanks for all your effort here!

2020-11-05 15:50 UTC, ChrisB9 commented on .travis.yml
>        env: COMPOSER_OPTS="--ignore-platform-reqs"
i'd say we limit this the only requirement we really want to disable
```suggestion
      env: COMPOSER_OPTS="--ignore-platform-req=php"
```

2020-11-06 13:30 UTC, dshoreman commented
@ChrisB9 Good idea to limit the ignores, committed that now so touch wood it'll all pass soon and it won't flag anything else!

2020-11-06 17:09 UTC, ChrisB9 approved these changes

2020-11-06 17:11 UTC, merged